[tool.poetry]
name = "jxl"
version = "0.3.3"
description = ""
authors = ["dayn9t <dayn9t@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.12"
rustshed = "*"
pydantic = "*"
typer = "*"
loguru = "*"

jcx = "*"
jvi = "*"
js4 = { path = "/home/jiang/py/js4" }

ultralytics = "*"
onnxruntime = "*"
onnx = "*"

[tool.poetry.group.test.dependencies]
pytest = "*"

[tool.poetry.group.dev.dependencies]
black = "*"
mypy = "*"
pyinstaller = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
