[project]
name = "jxl"
version = "0.4.2"
description = ""
readme = "README.md"
authors = [
    { name = "dayn9t", email = "dayn9t@gmail.com" }
]
requires-python = "~=3.12"

dependencies = [
    "jcx @ file:///home/jiang/py/jcx",
    "jvi @ file:///home/jiang/py/jvi",

    "rustshed",
    "pydantic",
    "typer",
    "loguru",
    "ultralytics",
    "onnxruntime",
    "onnx",
]


[tool.poetry.scripts]
jxl_label = "jxl.bin.jxl_label:main"
jxl_prop = "jxl.bin.jxl_prop:main"
jxl_sample = "jxl.bin.jxl_sample:main"


[tool.poetry.group.test.dependencies]
pytest = "*"


[tool.poetry.group.dev.dependencies]
black = "*"
pyinstaller = "*"
mypy = "*"
pre-commit = "*"
nuitka = "*"


[tool.ruff]
ignore = ["F403", "F405"]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
