[project]
name = "jxl"
version = "0.4.0"
description = ""
readme = "README.md"
authors = [
    { name = "dayn9t", email = "dayn9t@gmail.com" }
]
requires-python = "~=3.12"
dependencies = [
    "jcx @ file:///home/jiang/py/jcx",
    "jvi @ file:///home/jiang/py/jvi",

    "rustshed",
    "pydantic",
    "typer",
    "loguru"
    ,
    "ultralytics",
    "onnxruntime",
    "onnx",
    "jcx",
    "jvi",
]


[tool.poetry.group.test.dependencies]
pytest = "*"

[tool.poetry.group.dev.dependencies]
black = "*"
mypy = "*"
pyinstaller = "*"

[tool.ruff]
ignore = ["F403", "F405"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
