[tool.poetry]
name = "jxl"
version = "0.3.3"
description = ""
authors = ["dayn9t <dayn9t@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.12"
rustshed = "*"
pydantic = "*"
typer = "*"
loguru = "*"

jcx = { path = "/home/jiang/py/jcx" }
jvi = { path = "/home/jiang/py/jvi" }

ultralytics = "*"
onnxruntime = "*"
onnx = "*"

[tool.poetry.group.test.dependencies]
pytest = "*"

[tool.poetry.group.dev.dependencies]
black = "*"
mypy = "*"
pyinstaller = "*"

[tool.ruff]
ignore = ["F403", "F405"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
