[tool.poetry]
name = "jxl"
version = "0.3.1"
description = ""
authors = ["dayn9t <dayn9t@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.12"
rustshed = "*"

jcx = { path = "/home/jiang/py/jcx" }
jvi = { path = "/home/jiang/py/jvi" }
pydantic = "*"



[tool.poetry.group.test.dependencies]
pytest = "*"

[tool.poetry.group.dev.dependencies]
black = "*"
pyinstaller = "*"
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
